### ISSUE TITLE
implement cockroachdb to server code

### ISSUE THREAD

**Issue by Hitscotty** [Jayovergo/looper#6]
we need a database and we want to use cockroach db for our data storage

**Comment by willyhill** [comment]
Command Line

1. curl https://binaries.cockroachdb.com/cockroach-v21.2.5.darwin-10.9-amd64.tgz | tar -xz; sudo cp -i cockroach-v21.2.5.darwin-10.9-amd64/cockroach /usr/local/bin/
2. cockroach sql --url "postgresql://william:9-k9tXsoIpS1GbMYdNP7kw@free-tier11.gcp-us-east1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster%3Dloopers-table-216"

Connection string

1. curl --create-dirs -o $HOME/.postgresql/root.crt -O https://cockroachlabs.cloud/clusters/bfd0c0d8-f3c5-46b2-9694-e19b37fcd9f4/cert
2. postgresql://william:9-k9tXsoIpS1GbMYdNP7kw@free-tier11.gcp-us-east1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster%3Dloopers-table-216

Connection Parameters

- username = william
- host = free-tier11.gcp-us-east1.cockroachlabs.cloud
- port = 26257
- database = loopers-table-216.defaultdb
- password = 9-k9tXsoIpS1GbMYdNP7kw

import into terminal for connecting it to the server... Do each line in order...
